### ISSUE TITLE
Create script for resetting/deleting user data

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#740] opened 2023-08-14 20:36 UTC
As we embark upon the QA phase of development for certain features, it would be nice to be able to reset a user back to a blank state. In its barest form, a script that could delete all data associated with a user's account would be great!

- sites where the user is either the sole manager or sole member and associated data
- projects where the user is either the sole manager or sole member
- user profile data, tokens, settings, etc.

**Comment by ltseng** [comment] 2023-08-29 20:28
Audit log needs a record of who accomplished what action for regulatory compliance. If a user is deleted, we have a problem of losing the "who" part of that.

**Option 1:**
Log the user ID and name/email in every entry so that when a user is deleted, there is still a record of who accomplished each action in the past within each audit log entry associated with that user.

**Option 2:**
Just log the user ID in every entry, then at the time of deletion, log an additional row saying that, at the time of deletion, user x was "Firstname Lastname" and their email was "placeholder@email.com." Then, the person reviewing the audit log would need to look for this row to correlate past actions with the deleted user.

Option 2 offers more protections for user privacy and data after deletion, i.e. involves more steps. Option 1 is more usable.

Decided upon option 2.

**Comment by paulschreiber** [comment] 2023-08-31 22:33
Script to delete sites/projects/users: https://github.com/techmatters/terraso-backend/pull/776

**Comment by DerekCaelin** [comment] 2024-08-19 15:03
Now a duplicate of: 
- https://github.com/techmatters/terraso-backend/issues/1346

**Closed by DerekCaelin** 2024-08-19 15:03 UTC
