### ISSUE TITLE
Build/retrieve list of possible soil names and ecological site IDs/names

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#1097] opened 2024-01-09 21:29 UTC
Designs may need updating, but this task involves:
- Building some sort of database with all of the possible US soil names (will need a different one for the international app)
- Build some sort of database with all of the possible ecological site IDs/names in the US.
- Build a mapping between the soil names and ecological site IDs/names, understanding that:
  - some soils have no ecological site ID/name match
  - some soils have multiple ecological site IDs/names

**Comment by DerekCaelin** [comment] 2024-04-23 17:28
Closed as this is now a duplicate of:
- https://github.com/techmatters/terraso-product/issues/653

**Closed by DerekCaelin** 2024-04-23 17:28 UTC
Labels: slim MVP
